version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: ticketleader-db
    environment:
      POSTGRES_DB: ticketleader
      POSTGRES_USER: ticketleader
      POSTGRES_PASSWORD: ticketleader
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ticketleader -d ticketleader"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: